// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Retourne un JWT token",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessGetOneRequest"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "401": {
                        "description": "Données de connexion invalides",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "404": {
                        "description": "Utilisateur non trouvé",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/mainTypes": {
            "get": {
                "description": "Retrieve a list of all main types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MainType"
                ],
                "summary": "Get all main types",
                "responses": {
                    "201": {
                        "description": "Récupérer toutes les catégories",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessGetAllRequest"
                        }
                    },
                    "400": {
                        "description": "Échec de la récupération des catégories",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new main type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MainType"
                ],
                "summary": "Create mainType",
                "parameters": [
                    {
                        "description": "mainType payload",
                        "name": "mainType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mainType.CreateMainTypeDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Catégorie créé avec succés",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessCreateRequest"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "409": {
                        "description": "Catégorie déjà existante",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/subTypes": {
            "get": {
                "description": "Retrieve a list of all sub types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubType"
                ],
                "summary": "Get all subTypes",
                "responses": {
                    "201": {
                        "description": "Récupérer toutes les sous-catégories",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessGetAllRequest"
                        }
                    },
                    "400": {
                        "description": "Échec de la récupération des sous-catégories",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new sub type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubType"
                ],
                "summary": "Create subType",
                "parameters": [
                    {
                        "description": "subType payload",
                        "name": "subType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subType.CreateSubTypeDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Sous-catégorie créé avec succés",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessCreateRequest"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "409": {
                        "description": "Sous-catégorie déjà existante",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/subTypes/{mainTypeId}": {
            "get": {
                "description": "Retrieve a list of all sub types for a specific main type ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SubType"
                ],
                "summary": "Get all subTypes by main type ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "MainType ID",
                        "name": "mainTypeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Récupérer toutes les sous-catégories d'une catégorie",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessGetAllRequest"
                        }
                    },
                    "400": {
                        "description": "Échec de la récupération des sous-catégories",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Retrieve a list of all users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "201": {
                        "description": "Récupérer tous les utilisateurs",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessGetAllRequest"
                        }
                    },
                    "400": {
                        "description": "Échec de la récupération des utilisateurs",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "User payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Utilisateur créé avec succés",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessCreateRequest"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "409": {
                        "description": "Utilisateur déjà existant",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/users/{email}": {
            "get": {
                "description": "Retrieve a user account by email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Récupérer un utilisateur par email",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessGetAllRequest"
                        }
                    },
                    "400": {
                        "description": "Échec de la récupération de l'utilisateur",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "404": {
                        "description": "Utilisateur non trouvé",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user account by email",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user by email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User Email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Utilisateur supprimé avec succés",
                        "schema": {
                            "$ref": "#/definitions/request.SuccessDeleteRequest"
                        }
                    },
                    "400": {
                        "description": "Email invalide",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "404": {
                        "description": "Utilisateur non trouvé",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/request.ErrorRequest"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginDTO": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "lucasmadranges@gmail.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 12,
                    "example": "Azertye789456\u0026!"
                }
            }
        },
        "mainType.CreateMainTypeDto": {
            "type": "object",
            "required": [
                "color",
                "name"
            ],
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#000000"
                },
                "name": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "Restaurant"
                }
            }
        },
        "request.ErrorRequest": {
            "type": "object",
            "properties": {
                "explicit": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "request.SuccessCreateRequest": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "request.SuccessDeleteRequest": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 0
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "request.SuccessGetAllRequest": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "request.SuccessGetOneRequest": {
            "type": "object",
            "properties": {
                "data": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "subType.CreateSubTypeDto": {
            "type": "object",
            "required": [
                "color",
                "main_type_id",
                "name"
            ],
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#000000"
                },
                "main_type_id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 25,
                    "example": "Buffet à volonté"
                }
            }
        },
        "user.CreateUserDTO": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "password"
            ],
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://example.com/"
                },
                "email": {
                    "type": "string",
                    "example": "lucasmadranges@gmail.com"
                },
                "firstname": {
                    "type": "string",
                    "example": "Lucas"
                },
                "lastname": {
                    "type": "string",
                    "example": "Madranges"
                },
                "password": {
                    "type": "string",
                    "minLength": 12,
                    "example": "Azertye789456\u0026!"
                },
                "role": {
                    "enum": [
                        "admin",
                        "user"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/user.Role"
                        }
                    ],
                    "example": "user"
                }
            }
        },
        "user.Role": {
            "type": "string",
            "enum": [
                "user",
                "admin",
                "user"
            ],
            "x-enum-varnames": [
                "DefaultRole",
                "RoleAdmin",
                "RoleUser"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Fiber API",
	Description:      "API avec Fiber, Ent et Swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
