basePath: /
definitions:
  auth.LoginDTO:
    properties:
      email:
        example: lucasmadranges@gmail.com
        type: string
      password:
        example: Azertye789456&!
        minLength: 12
        type: string
    required:
      - email
      - password
    type: object
  request.ErrorRequest:
    properties:
      explicit:
        example: Failed to retieve users due to database timeout
        type: string
      message:
        example: Failed to retrieve users
        type: string
      success:
        example: false
        type: boolean
    type: object
  request.SuccessCreateRequest:
    properties:
      data: {}
      success:
        example: true
        type: boolean
    type: object
  request.SuccessDeleteRequest:
    properties:
      count:
        example: 0
        type: integer
      success:
        example: true
        type: boolean
    type: object
  request.SuccessGetAllRequest:
    properties:
      data: {}
      success:
        example: true
        type: boolean
    type: object
  user.CreateUserDTO:
    properties:
      avatar:
        example: https://example.com/
        type: string
      email:
        example: lucasmadranges@gmail.com
        type: string
      firstname:
        example: Lucas
        minLength: 2
        type: string
      lastname:
        example: Madranges
        minLength: 2
        type: string
      password:
        example: Azertye789456&!
        minLength: 12
        type: string
      role:
        allOf:
          - $ref: '#/definitions/user.Role'
        enum:
          - admin
          - user
        example: user
    required:
      - email
      - firstname
      - lastname
      - password
    type: object
  user.Role:
    enum:
      - user
      - admin
      - user
    type: string
    x-enum-varnames:
      - DefaultRole
      - RoleAdmin
      - RoleUser
host: localhost:4000
info:
  contact: {}
  description: API avec Fiber, Ent et Swagger
  title: Go Fiber API
  version: '1.0'
paths:
  /auth/login:
    post:
      consumes:
        - application/json
      description: Authenticate user with email and password
      parameters:
        - description: Login credentials
          in: body
          name: credentials
          required: true
          schema:
            $ref: '#/definitions/auth.LoginDTO'
      produces:
        - application/json
      responses:
        '200':
          description: Returns JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        '400':
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        '401':
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
        - auth
  /users:
    get:
      description: Retrieve a list of all users
      produces:
        - application/json
      responses:
        '201':
          description: List of users
          schema:
            items:
              $ref: '#/definitions/request.SuccessGetAllRequest'
            type: array
        '400':
          description: Failed to retrieve users
          schema:
            $ref: '#/definitions/request.ErrorRequest'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/request.ErrorRequest'
      summary: Get all users
      tags:
        - Users
    post:
      consumes:
        - application/json
      description: Create a new user account
      parameters:
        - description: User payload
          in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/user.CreateUserDTO'
      produces:
        - application/json
      responses:
        '201':
          description: User created successfully
          schema:
            $ref: '#/definitions/request.SuccessCreateRequest'
        '400':
          description: Invalid request body
          schema:
            $ref: '#/definitions/request.ErrorRequest'
        '409':
          description: User already exists
          schema:
            $ref: '#/definitions/request.ErrorRequest'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/request.ErrorRequest'
      summary: Create user
      tags:
        - Users
  /users/{email}:
    delete:
      description: Delete a user account by email
      parameters:
        - description: User Email
          in: path
          name: email
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User deleted successfully
          schema:
            $ref: '#/definitions/request.SuccessDeleteRequest'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/request.ErrorRequest'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/request.ErrorRequest'
      summary: Delete user by email
      tags:
        - Users
    get:
      description: Retrieve a user account by email
      parameters:
        - description: User Email
          in: path
          name: email
          required: true
          type: string
      produces:
        - application/json
      responses:
        '201':
          description: List of users
          schema:
            items:
              $ref: '#/definitions/request.SuccessGetAllRequest'
            type: array
        '400':
          description: Failed to retrieve users
          schema:
            $ref: '#/definitions/request.ErrorRequest'
        '500':
          description: Internal server error
          schema:
            $ref: '#/definitions/request.ErrorRequest'
      summary: Get user by email
      tags:
        - Users
swagger: '2.0'
