services:
  database-mapmemory:
    image: postgres:16
    container_name: db_mapmemory
    ports:
      - "5432:5432"
    volumes:
      - db_users_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_users_data:
