services:
  appweb-mapmemory:
    image: appweb:dev
    container_name: appweb-mapmemory
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - gateway-mapmemory
    networks:
      - MapMemoryNetworks

  gateway-mapmemory:
    image: gateway:dev
    container_name: gateway-mapmemory
    ports:
      - '4000:4000'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - users-mapmemory
      - memory-mapmemory
      - friends-mapmemory
    networks:
      - MapMemoryNetworks

  users-mapmemory:
    image: users:dev
    container_name: users-mapmemory
    ports:
      - '4001:4001'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db-mapmemory
    networks:
      - MapMemoryNetworks

  memory-mapmemory:
    image: memory:dev
    container_name: memory-mapmemory
    ports:
      - '4002:4002'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db-mapmemory
    networks:
      - MapMemoryNetworks

  friends-mapmemory:
    image: friends:dev
    container_name: friends-mapmemory
    ports:
      - '4003:4003'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db-mapmemory
    networks:
      - MapMemoryNetworks

  db-mapmemory:
    image: postgres:16
    container_name: db-mapmemory
    ports:
      - '5432:5432'
    volumes:
      - db_users_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - MapMemoryNetworks

volumes:
  db_users_data:

networks:
  MapMemoryNetworks:
    driver: bridge
