// Code generated by ent, DO NOT EDIT.

package maintype

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the maintype type in the database.
	Label = "main_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeMemories holds the string denoting the memories edge name in mutations.
	EdgeMemories = "memories"
	// EdgeSubTypes holds the string denoting the sub_types edge name in mutations.
	EdgeSubTypes = "sub_types"
	// Table holds the table name of the maintype in the database.
	Table = "main_types"
	// MemoriesTable is the table that holds the memories relation/edge.
	MemoriesTable = "memories"
	// MemoriesInverseTable is the table name for the Memory entity.
	// It exists in this package in order to avoid circular dependency with the "memory" package.
	MemoriesInverseTable = "memories"
	// MemoriesColumn is the table column denoting the memories relation/edge.
	MemoriesColumn = "main_type_id"
	// SubTypesTable is the table that holds the sub_types relation/edge.
	SubTypesTable = "sub_types"
	// SubTypesInverseTable is the table name for the SubType entity.
	// It exists in this package in order to avoid circular dependency with the "subtype" package.
	SubTypesInverseTable = "sub_types"
	// SubTypesColumn is the table column denoting the sub_types relation/edge.
	SubTypesColumn = "sub_type_id"
)

// Columns holds all SQL columns for maintype fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the MainType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByMemoriesCount orders the results by memories count.
func ByMemoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemoriesStep(), opts...)
	}
}

// ByMemories orders the results by memories terms.
func ByMemories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubTypesCount orders the results by sub_types count.
func BySubTypesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubTypesStep(), opts...)
	}
}

// BySubTypes orders the results by sub_types terms.
func BySubTypes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubTypesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMemoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, MemoriesTable, MemoriesColumn),
	)
}
func newSubTypesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubTypesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubTypesTable, SubTypesColumn),
	)
}
