// Code generated by ent, DO NOT EDIT.

package memory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memory type in the database.
	Label = "memory"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMainType holds the string denoting the main_type edge name in mutations.
	EdgeMainType = "main_type"
	// EdgeSubType holds the string denoting the sub_type edge name in mutations.
	EdgeSubType = "sub_type"
	// Table holds the table name of the memory in the database.
	Table = "memories"
	// MainTypeTable is the table that holds the main_type relation/edge.
	MainTypeTable = "memories"
	// MainTypeInverseTable is the table name for the MainType entity.
	// It exists in this package in order to avoid circular dependency with the "maintype" package.
	MainTypeInverseTable = "main_types"
	// MainTypeColumn is the table column denoting the main_type relation/edge.
	MainTypeColumn = "main_type_id"
	// SubTypeTable is the table that holds the sub_type relation/edge.
	SubTypeTable = "memories"
	// SubTypeInverseTable is the table name for the SubType entity.
	// It exists in this package in order to avoid circular dependency with the "subtype" package.
	SubTypeInverseTable = "sub_types"
	// SubTypeColumn is the table column denoting the sub_type relation/edge.
	SubTypeColumn = "sub_type_id"
)

// Columns holds all SQL columns for memory fields.
var Columns = []string{
	FieldID,
	FieldLabel,
	FieldDescription,
	FieldPrice,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "memories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"main_type_id",
	"sub_type_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LabelValidator is a validator for the "label" field. It is called by the builders before save.
	LabelValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Memory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMainTypeField orders the results by main_type field.
func ByMainTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMainTypeStep(), sql.OrderByField(field, opts...))
	}
}

// BySubTypeField orders the results by sub_type field.
func BySubTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubTypeStep(), sql.OrderByField(field, opts...))
	}
}
func newMainTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MainTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, MainTypeTable, MainTypeColumn),
	)
}
func newSubTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SubTypeTable, SubTypeColumn),
	)
}
