// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/predicate"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// MainTypeQuery is the builder for querying MainType entities.
type MainTypeQuery struct {
	config
	ctx          *QueryContext
	order        []maintype.OrderOption
	inters       []Interceptor
	predicates   []predicate.MainType
	withMemories *MemoryQuery
	withSubTypes *SubTypeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MainTypeQuery builder.
func (_q *MainTypeQuery) Where(ps ...predicate.MainType) *MainTypeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MainTypeQuery) Limit(limit int) *MainTypeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MainTypeQuery) Offset(offset int) *MainTypeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MainTypeQuery) Unique(unique bool) *MainTypeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MainTypeQuery) Order(o ...maintype.OrderOption) *MainTypeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMemories chains the current query on the "memories" edge.
func (_q *MainTypeQuery) QueryMemories() *MemoryQuery {
	query := (&MemoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(maintype.Table, maintype.FieldID, selector),
			sqlgraph.To(memory.Table, memory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, maintype.MemoriesTable, maintype.MemoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubTypes chains the current query on the "sub_types" edge.
func (_q *MainTypeQuery) QuerySubTypes() *SubTypeQuery {
	query := (&SubTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(maintype.Table, maintype.FieldID, selector),
			sqlgraph.To(subtype.Table, subtype.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, maintype.SubTypesTable, maintype.SubTypesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MainType entity from the query.
// Returns a *NotFoundError when no MainType was found.
func (_q *MainTypeQuery) First(ctx context.Context) (*MainType, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{maintype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MainTypeQuery) FirstX(ctx context.Context) *MainType {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MainType ID from the query.
// Returns a *NotFoundError when no MainType ID was found.
func (_q *MainTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{maintype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MainTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MainType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MainType entity is found.
// Returns a *NotFoundError when no MainType entities are found.
func (_q *MainTypeQuery) Only(ctx context.Context) (*MainType, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{maintype.Label}
	default:
		return nil, &NotSingularError{maintype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MainTypeQuery) OnlyX(ctx context.Context) *MainType {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MainType ID in the query.
// Returns a *NotSingularError when more than one MainType ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MainTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{maintype.Label}
	default:
		err = &NotSingularError{maintype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MainTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MainTypes.
func (_q *MainTypeQuery) All(ctx context.Context) ([]*MainType, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MainType, *MainTypeQuery]()
	return withInterceptors[[]*MainType](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MainTypeQuery) AllX(ctx context.Context) []*MainType {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MainType IDs.
func (_q *MainTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(maintype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MainTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MainTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MainTypeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MainTypeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MainTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MainTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MainTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MainTypeQuery) Clone() *MainTypeQuery {
	if _q == nil {
		return nil
	}
	return &MainTypeQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]maintype.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.MainType{}, _q.predicates...),
		withMemories: _q.withMemories.Clone(),
		withSubTypes: _q.withSubTypes.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMemories tells the query-builder to eager-load the nodes that are connected to
// the "memories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MainTypeQuery) WithMemories(opts ...func(*MemoryQuery)) *MainTypeQuery {
	query := (&MemoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMemories = query
	return _q
}

// WithSubTypes tells the query-builder to eager-load the nodes that are connected to
// the "sub_types" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MainTypeQuery) WithSubTypes(opts ...func(*SubTypeQuery)) *MainTypeQuery {
	query := (&SubTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubTypes = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MainType.Query().
//		GroupBy(maintype.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MainTypeQuery) GroupBy(field string, fields ...string) *MainTypeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MainTypeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = maintype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.MainType.Query().
//		Select(maintype.FieldName).
//		Scan(ctx, &v)
func (_q *MainTypeQuery) Select(fields ...string) *MainTypeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MainTypeSelect{MainTypeQuery: _q}
	sbuild.label = maintype.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MainTypeSelect configured with the given aggregations.
func (_q *MainTypeQuery) Aggregate(fns ...AggregateFunc) *MainTypeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MainTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !maintype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MainTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MainType, error) {
	var (
		nodes       = []*MainType{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMemories != nil,
			_q.withSubTypes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MainType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MainType{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMemories; query != nil {
		if err := _q.loadMemories(ctx, query, nodes,
			func(n *MainType) { n.Edges.Memories = []*Memory{} },
			func(n *MainType, e *Memory) { n.Edges.Memories = append(n.Edges.Memories, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubTypes; query != nil {
		if err := _q.loadSubTypes(ctx, query, nodes,
			func(n *MainType) { n.Edges.SubTypes = []*SubType{} },
			func(n *MainType, e *SubType) { n.Edges.SubTypes = append(n.Edges.SubTypes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MainTypeQuery) loadMemories(ctx context.Context, query *MemoryQuery, nodes []*MainType, init func(*MainType), assign func(*MainType, *Memory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MainType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Memory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(maintype.MemoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.main_type_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "main_type_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "main_type_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *MainTypeQuery) loadSubTypes(ctx context.Context, query *SubTypeQuery, nodes []*MainType, init func(*MainType), assign func(*MainType, *SubType)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*MainType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.SubType(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(maintype.SubTypesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sub_type_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "sub_type_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sub_type_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *MainTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MainTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(maintype.Table, maintype.Columns, sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, maintype.FieldID)
		for i := range fields {
			if fields[i] != maintype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MainTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(maintype.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = maintype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MainTypeGroupBy is the group-by builder for MainType entities.
type MainTypeGroupBy struct {
	selector
	build *MainTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MainTypeGroupBy) Aggregate(fns ...AggregateFunc) *MainTypeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MainTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MainTypeQuery, *MainTypeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MainTypeGroupBy) sqlScan(ctx context.Context, root *MainTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MainTypeSelect is the builder for selecting fields of MainType entities.
type MainTypeSelect struct {
	*MainTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MainTypeSelect) Aggregate(fns ...AggregateFunc) *MainTypeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MainTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MainTypeQuery, *MainTypeSelect](ctx, _s.MainTypeQuery, _s, _s.inters, v)
}

func (_s *MainTypeSelect) sqlScan(ctx context.Context, root *MainTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
