// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
)

// MainType is the model entity for the MainType schema.
type MainType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MainTypeQuery when eager-loading is set.
	Edges        MainTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MainTypeEdges holds the relations/edges for other nodes in the graph.
type MainTypeEdges struct {
	// Memories holds the value of the memories edge.
	Memories []*Memory `json:"memories,omitempty"`
	// SubTypes holds the value of the sub_types edge.
	SubTypes []*SubType `json:"sub_types,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MemoriesOrErr returns the Memories value or an error if the edge
// was not loaded in eager-loading.
func (e MainTypeEdges) MemoriesOrErr() ([]*Memory, error) {
	if e.loadedTypes[0] {
		return e.Memories, nil
	}
	return nil, &NotLoadedError{edge: "memories"}
}

// SubTypesOrErr returns the SubTypes value or an error if the edge
// was not loaded in eager-loading.
func (e MainTypeEdges) SubTypesOrErr() ([]*SubType, error) {
	if e.loadedTypes[1] {
		return e.SubTypes, nil
	}
	return nil, &NotLoadedError{edge: "sub_types"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MainType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case maintype.FieldID:
			values[i] = new(sql.NullInt64)
		case maintype.FieldLabel, maintype.FieldColor:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MainType fields.
func (_m *MainType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case maintype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case maintype.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case maintype.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MainType.
// This includes values selected through modifiers, order, etc.
func (_m *MainType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMemories queries the "memories" edge of the MainType entity.
func (_m *MainType) QueryMemories() *MemoryQuery {
	return NewMainTypeClient(_m.config).QueryMemories(_m)
}

// QuerySubTypes queries the "sub_types" edge of the MainType entity.
func (_m *MainType) QuerySubTypes() *SubTypeQuery {
	return NewMainTypeClient(_m.config).QuerySubTypes(_m)
}

// Update returns a builder for updating this MainType.
// Note that you need to call MainType.Unwrap() before calling this method if this MainType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MainType) Update() *MainTypeUpdateOne {
	return NewMainTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MainType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MainType) Unwrap() *MainType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MainType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MainType) String() string {
	var builder strings.Builder
	builder.WriteString("MainType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteByte(')')
	return builder.String()
}

// MainTypes is a parsable slice of MainType.
type MainTypes []*MainType
