// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/predicate"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// MainTypeUpdate is the builder for updating MainType entities.
type MainTypeUpdate struct {
	config
	hooks    []Hook
	mutation *MainTypeMutation
}

// Where appends a list predicates to the MainTypeUpdate builder.
func (_u *MainTypeUpdate) Where(ps ...predicate.MainType) *MainTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MainTypeUpdate) SetName(v string) *MainTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MainTypeUpdate) SetNillableName(v *string) *MainTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_u *MainTypeUpdate) AddMemoryIDs(ids ...int) *MainTypeUpdate {
	_u.mutation.AddMemoryIDs(ids...)
	return _u
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_u *MainTypeUpdate) AddMemories(v ...*Memory) *MainTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryIDs(ids...)
}

// AddSubTypeIDs adds the "sub_types" edge to the SubType entity by IDs.
func (_u *MainTypeUpdate) AddSubTypeIDs(ids ...int) *MainTypeUpdate {
	_u.mutation.AddSubTypeIDs(ids...)
	return _u
}

// AddSubTypes adds the "sub_types" edges to the SubType entity.
func (_u *MainTypeUpdate) AddSubTypes(v ...*SubType) *MainTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubTypeIDs(ids...)
}

// Mutation returns the MainTypeMutation object of the builder.
func (_u *MainTypeUpdate) Mutation() *MainTypeMutation {
	return _u.mutation
}

// ClearMemories clears all "memories" edges to the Memory entity.
func (_u *MainTypeUpdate) ClearMemories() *MainTypeUpdate {
	_u.mutation.ClearMemories()
	return _u
}

// RemoveMemoryIDs removes the "memories" edge to Memory entities by IDs.
func (_u *MainTypeUpdate) RemoveMemoryIDs(ids ...int) *MainTypeUpdate {
	_u.mutation.RemoveMemoryIDs(ids...)
	return _u
}

// RemoveMemories removes "memories" edges to Memory entities.
func (_u *MainTypeUpdate) RemoveMemories(v ...*Memory) *MainTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryIDs(ids...)
}

// ClearSubTypes clears all "sub_types" edges to the SubType entity.
func (_u *MainTypeUpdate) ClearSubTypes() *MainTypeUpdate {
	_u.mutation.ClearSubTypes()
	return _u
}

// RemoveSubTypeIDs removes the "sub_types" edge to SubType entities by IDs.
func (_u *MainTypeUpdate) RemoveSubTypeIDs(ids ...int) *MainTypeUpdate {
	_u.mutation.RemoveSubTypeIDs(ids...)
	return _u
}

// RemoveSubTypes removes "sub_types" edges to SubType entities.
func (_u *MainTypeUpdate) RemoveSubTypes(v ...*SubType) *MainTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubTypeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MainTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MainTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MainTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MainTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MainTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := maintype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MainType.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MainTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(maintype.Table, maintype.Columns, sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(maintype.FieldName, field.TypeString, value)
	}
	if _u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoriesIDs(); len(nodes) > 0 && !_u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubTypesIDs(); len(nodes) > 0 && !_u.mutation.SubTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{maintype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MainTypeUpdateOne is the builder for updating a single MainType entity.
type MainTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MainTypeMutation
}

// SetName sets the "name" field.
func (_u *MainTypeUpdateOne) SetName(v string) *MainTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MainTypeUpdateOne) SetNillableName(v *string) *MainTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_u *MainTypeUpdateOne) AddMemoryIDs(ids ...int) *MainTypeUpdateOne {
	_u.mutation.AddMemoryIDs(ids...)
	return _u
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_u *MainTypeUpdateOne) AddMemories(v ...*Memory) *MainTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryIDs(ids...)
}

// AddSubTypeIDs adds the "sub_types" edge to the SubType entity by IDs.
func (_u *MainTypeUpdateOne) AddSubTypeIDs(ids ...int) *MainTypeUpdateOne {
	_u.mutation.AddSubTypeIDs(ids...)
	return _u
}

// AddSubTypes adds the "sub_types" edges to the SubType entity.
func (_u *MainTypeUpdateOne) AddSubTypes(v ...*SubType) *MainTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubTypeIDs(ids...)
}

// Mutation returns the MainTypeMutation object of the builder.
func (_u *MainTypeUpdateOne) Mutation() *MainTypeMutation {
	return _u.mutation
}

// ClearMemories clears all "memories" edges to the Memory entity.
func (_u *MainTypeUpdateOne) ClearMemories() *MainTypeUpdateOne {
	_u.mutation.ClearMemories()
	return _u
}

// RemoveMemoryIDs removes the "memories" edge to Memory entities by IDs.
func (_u *MainTypeUpdateOne) RemoveMemoryIDs(ids ...int) *MainTypeUpdateOne {
	_u.mutation.RemoveMemoryIDs(ids...)
	return _u
}

// RemoveMemories removes "memories" edges to Memory entities.
func (_u *MainTypeUpdateOne) RemoveMemories(v ...*Memory) *MainTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryIDs(ids...)
}

// ClearSubTypes clears all "sub_types" edges to the SubType entity.
func (_u *MainTypeUpdateOne) ClearSubTypes() *MainTypeUpdateOne {
	_u.mutation.ClearSubTypes()
	return _u
}

// RemoveSubTypeIDs removes the "sub_types" edge to SubType entities by IDs.
func (_u *MainTypeUpdateOne) RemoveSubTypeIDs(ids ...int) *MainTypeUpdateOne {
	_u.mutation.RemoveSubTypeIDs(ids...)
	return _u
}

// RemoveSubTypes removes "sub_types" edges to SubType entities.
func (_u *MainTypeUpdateOne) RemoveSubTypes(v ...*SubType) *MainTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubTypeIDs(ids...)
}

// Where appends a list predicates to the MainTypeUpdate builder.
func (_u *MainTypeUpdateOne) Where(ps ...predicate.MainType) *MainTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MainTypeUpdateOne) Select(field string, fields ...string) *MainTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MainType entity.
func (_u *MainTypeUpdateOne) Save(ctx context.Context) (*MainType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MainTypeUpdateOne) SaveX(ctx context.Context) *MainType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MainTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MainTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MainTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := maintype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "MainType.name": %w`, err)}
		}
	}
	return nil
}

func (_u *MainTypeUpdateOne) sqlSave(ctx context.Context) (_node *MainType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(maintype.Table, maintype.Columns, sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MainType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, maintype.FieldID)
		for _, f := range fields {
			if !maintype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != maintype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(maintype.FieldName, field.TypeString, value)
	}
	if _u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoriesIDs(); len(nodes) > 0 && !_u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubTypesIDs(); len(nodes) > 0 && !_u.mutation.SubTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MainType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{maintype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
