// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// MainTypeCreate is the builder for creating a MainType entity.
type MainTypeCreate struct {
	config
	mutation *MainTypeMutation
	hooks    []Hook
}

// SetLabel sets the "label" field.
func (_c *MainTypeCreate) SetLabel(v string) *MainTypeCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *MainTypeCreate) SetColor(v string) *MainTypeCreate {
	_c.mutation.SetColor(v)
	return _c
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_c *MainTypeCreate) AddMemoryIDs(ids ...int) *MainTypeCreate {
	_c.mutation.AddMemoryIDs(ids...)
	return _c
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_c *MainTypeCreate) AddMemories(v ...*Memory) *MainTypeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemoryIDs(ids...)
}

// AddSubTypeIDs adds the "sub_types" edge to the SubType entity by IDs.
func (_c *MainTypeCreate) AddSubTypeIDs(ids ...int) *MainTypeCreate {
	_c.mutation.AddSubTypeIDs(ids...)
	return _c
}

// AddSubTypes adds the "sub_types" edges to the SubType entity.
func (_c *MainTypeCreate) AddSubTypes(v ...*SubType) *MainTypeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubTypeIDs(ids...)
}

// Mutation returns the MainTypeMutation object of the builder.
func (_c *MainTypeCreate) Mutation() *MainTypeMutation {
	return _c.mutation
}

// Save creates the MainType in the database.
func (_c *MainTypeCreate) Save(ctx context.Context) (*MainType, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MainTypeCreate) SaveX(ctx context.Context) *MainType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MainTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MainTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MainTypeCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "MainType.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := maintype.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "MainType.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "MainType.color"`)}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := maintype.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "MainType.color": %w`, err)}
		}
	}
	return nil
}

func (_c *MainTypeCreate) sqlSave(ctx context.Context) (*MainType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MainTypeCreate) createSpec() (*MainType, *sqlgraph.CreateSpec) {
	var (
		_node = &MainType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(maintype.Table, sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(maintype.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(maintype.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if nodes := _c.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   maintype.MemoriesTable,
			Columns: []string{maintype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   maintype.SubTypesTable,
			Columns: []string{maintype.SubTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MainTypeCreateBulk is the builder for creating many MainType entities in bulk.
type MainTypeCreateBulk struct {
	config
	err      error
	builders []*MainTypeCreate
}

// Save creates the MainType entities in the database.
func (_c *MainTypeCreateBulk) Save(ctx context.Context) ([]*MainType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MainType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MainTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MainTypeCreateBulk) SaveX(ctx context.Context) []*MainType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MainTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MainTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
