// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// MemoryCreate is the builder for creating a Memory entity.
type MemoryCreate struct {
	config
	mutation *MemoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *MemoryCreate) SetName(v string) *MemoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MemoryCreate) SetDescription(v string) *MemoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableDescription(v *string) *MemoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *MemoryCreate) SetPrice(v float64) *MemoryCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoryCreate) SetCreatedAt(v time.Time) *MemoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableCreatedAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MemoryCreate) SetUpdatedAt(v time.Time) *MemoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MemoryCreate) SetNillableUpdatedAt(v *time.Time) *MemoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMainTypeID sets the "main_type" edge to the MainType entity by ID.
func (_c *MemoryCreate) SetMainTypeID(id int) *MemoryCreate {
	_c.mutation.SetMainTypeID(id)
	return _c
}

// SetMainType sets the "main_type" edge to the MainType entity.
func (_c *MemoryCreate) SetMainType(v *MainType) *MemoryCreate {
	return _c.SetMainTypeID(v.ID)
}

// SetSubTypeID sets the "sub_type" edge to the SubType entity by ID.
func (_c *MemoryCreate) SetSubTypeID(id int) *MemoryCreate {
	_c.mutation.SetSubTypeID(id)
	return _c
}

// SetSubType sets the "sub_type" edge to the SubType entity.
func (_c *MemoryCreate) SetSubType(v *SubType) *MemoryCreate {
	return _c.SetSubTypeID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_c *MemoryCreate) Mutation() *MemoryMutation {
	return _c.mutation
}

// Save creates the Memory in the database.
func (_c *MemoryCreate) Save(ctx context.Context) (*Memory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryCreate) SaveX(ctx context.Context) *Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := memory.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := memory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Memory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := memory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Memory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Memory.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := memory.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Memory.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Memory.price"`)}
	}
	if v, ok := _c.mutation.Price(); ok {
		if err := memory.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Memory.price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Memory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Memory.updated_at"`)}
	}
	if len(_c.mutation.MainTypeIDs()) == 0 {
		return &ValidationError{Name: "main_type", err: errors.New(`ent: missing required edge "Memory.main_type"`)}
	}
	if len(_c.mutation.SubTypeIDs()) == 0 {
		return &ValidationError{Name: "sub_type", err: errors.New(`ent: missing required edge "Memory.sub_type"`)}
	}
	return nil
}

func (_c *MemoryCreate) sqlSave(ctx context.Context) (*Memory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryCreate) createSpec() (*Memory, *sqlgraph.CreateSpec) {
	var (
		_node = &Memory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memory.Table, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(memory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(memory.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(memory.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(memory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MainTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.MainTypeTable,
			Columns: []string{memory.MainTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.main_type_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.SubTypeTable,
			Columns: []string{memory.SubTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.sub_type_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemoryCreateBulk is the builder for creating many Memory entities in bulk.
type MemoryCreateBulk struct {
	config
	err      error
	builders []*MemoryCreate
}

// Save creates the Memory entities in the database.
func (_c *MemoryCreateBulk) Save(ctx context.Context) ([]*Memory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Memory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryCreateBulk) SaveX(ctx context.Context) []*Memory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
