// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// Memory is the model entity for the Memory schema.
type Memory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemoryQuery when eager-loading is set.
	Edges        MemoryEdges `json:"edges"`
	main_type_id *int
	sub_type_id  *int
	selectValues sql.SelectValues
}

// MemoryEdges holds the relations/edges for other nodes in the graph.
type MemoryEdges struct {
	// MainType holds the value of the main_type edge.
	MainType *MainType `json:"main_type,omitempty"`
	// SubType holds the value of the sub_type edge.
	SubType *SubType `json:"sub_type,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MainTypeOrErr returns the MainType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemoryEdges) MainTypeOrErr() (*MainType, error) {
	if e.MainType != nil {
		return e.MainType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: maintype.Label}
	}
	return nil, &NotLoadedError{edge: "main_type"}
}

// SubTypeOrErr returns the SubType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemoryEdges) SubTypeOrErr() (*SubType, error) {
	if e.SubType != nil {
		return e.SubType, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: subtype.Label}
	}
	return nil, &NotLoadedError{edge: "sub_type"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Memory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memory.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case memory.FieldID:
			values[i] = new(sql.NullInt64)
		case memory.FieldName, memory.FieldDescription:
			values[i] = new(sql.NullString)
		case memory.FieldCreatedAt, memory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case memory.ForeignKeys[0]: // main_type_id
			values[i] = new(sql.NullInt64)
		case memory.ForeignKeys[1]: // sub_type_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Memory fields.
func (_m *Memory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case memory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case memory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case memory.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case memory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case memory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case memory.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field main_type_id", value)
			} else if value.Valid {
				_m.main_type_id = new(int)
				*_m.main_type_id = int(value.Int64)
			}
		case memory.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sub_type_id", value)
			} else if value.Valid {
				_m.sub_type_id = new(int)
				*_m.sub_type_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Memory.
// This includes values selected through modifiers, order, etc.
func (_m *Memory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMainType queries the "main_type" edge of the Memory entity.
func (_m *Memory) QueryMainType() *MainTypeQuery {
	return NewMemoryClient(_m.config).QueryMainType(_m)
}

// QuerySubType queries the "sub_type" edge of the Memory entity.
func (_m *Memory) QuerySubType() *SubTypeQuery {
	return NewMemoryClient(_m.config).QuerySubType(_m)
}

// Update returns a builder for updating this Memory.
// Note that you need to call Memory.Unwrap() before calling this method if this Memory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Memory) Update() *MemoryUpdateOne {
	return NewMemoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Memory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Memory) Unwrap() *Memory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Memory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Memory) String() string {
	var builder strings.Builder
	builder.WriteString("Memory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Memories is a parsable slice of Memory.
type Memories []*Memory
