// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/predicate"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// MemoryUpdate is the builder for updating Memory entities.
type MemoryUpdate struct {
	config
	hooks    []Hook
	mutation *MemoryMutation
}

// Where appends a list predicates to the MemoryUpdate builder.
func (_u *MemoryUpdate) Where(ps ...predicate.Memory) *MemoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MemoryUpdate) SetName(v string) *MemoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableName(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MemoryUpdate) SetDescription(v string) *MemoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillableDescription(v *string) *MemoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *MemoryUpdate) SetPrice(v float64) *MemoryUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *MemoryUpdate) SetNillablePrice(v *float64) *MemoryUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *MemoryUpdate) AddPrice(v float64) *MemoryUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryUpdate) SetUpdatedAt(v time.Time) *MemoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMainTypeID sets the "main_type" edge to the MainType entity by ID.
func (_u *MemoryUpdate) SetMainTypeID(id int) *MemoryUpdate {
	_u.mutation.SetMainTypeID(id)
	return _u
}

// SetMainType sets the "main_type" edge to the MainType entity.
func (_u *MemoryUpdate) SetMainType(v *MainType) *MemoryUpdate {
	return _u.SetMainTypeID(v.ID)
}

// SetSubTypeID sets the "sub_type" edge to the SubType entity by ID.
func (_u *MemoryUpdate) SetSubTypeID(id int) *MemoryUpdate {
	_u.mutation.SetSubTypeID(id)
	return _u
}

// SetSubType sets the "sub_type" edge to the SubType entity.
func (_u *MemoryUpdate) SetSubType(v *SubType) *MemoryUpdate {
	return _u.SetSubTypeID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_u *MemoryUpdate) Mutation() *MemoryMutation {
	return _u.mutation
}

// ClearMainType clears the "main_type" edge to the MainType entity.
func (_u *MemoryUpdate) ClearMainType() *MemoryUpdate {
	_u.mutation.ClearMainType()
	return _u
}

// ClearSubType clears the "sub_type" edge to the SubType entity.
func (_u *MemoryUpdate) ClearSubType() *MemoryUpdate {
	_u.mutation.ClearSubType()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := memory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Memory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := memory.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Memory.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := memory.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Memory.price": %w`, err)}
		}
	}
	if _u.mutation.MainTypeCleared() && len(_u.mutation.MainTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.main_type"`)
	}
	if _u.mutation.SubTypeCleared() && len(_u.mutation.SubTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.sub_type"`)
	}
	return nil
}

func (_u *MemoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memory.Table, memory.Columns, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(memory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(memory.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(memory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(memory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MainTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.MainTypeTable,
			Columns: []string{memory.MainTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MainTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.MainTypeTable,
			Columns: []string{memory.MainTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.SubTypeTable,
			Columns: []string{memory.SubTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.SubTypeTable,
			Columns: []string{memory.SubTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoryUpdateOne is the builder for updating a single Memory entity.
type MemoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoryMutation
}

// SetName sets the "name" field.
func (_u *MemoryUpdateOne) SetName(v string) *MemoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableName(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *MemoryUpdateOne) SetDescription(v string) *MemoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillableDescription(v *string) *MemoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *MemoryUpdateOne) SetPrice(v float64) *MemoryUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *MemoryUpdateOne) SetNillablePrice(v *float64) *MemoryUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *MemoryUpdateOne) AddPrice(v float64) *MemoryUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryUpdateOne) SetUpdatedAt(v time.Time) *MemoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMainTypeID sets the "main_type" edge to the MainType entity by ID.
func (_u *MemoryUpdateOne) SetMainTypeID(id int) *MemoryUpdateOne {
	_u.mutation.SetMainTypeID(id)
	return _u
}

// SetMainType sets the "main_type" edge to the MainType entity.
func (_u *MemoryUpdateOne) SetMainType(v *MainType) *MemoryUpdateOne {
	return _u.SetMainTypeID(v.ID)
}

// SetSubTypeID sets the "sub_type" edge to the SubType entity by ID.
func (_u *MemoryUpdateOne) SetSubTypeID(id int) *MemoryUpdateOne {
	_u.mutation.SetSubTypeID(id)
	return _u
}

// SetSubType sets the "sub_type" edge to the SubType entity.
func (_u *MemoryUpdateOne) SetSubType(v *SubType) *MemoryUpdateOne {
	return _u.SetSubTypeID(v.ID)
}

// Mutation returns the MemoryMutation object of the builder.
func (_u *MemoryUpdateOne) Mutation() *MemoryMutation {
	return _u.mutation
}

// ClearMainType clears the "main_type" edge to the MainType entity.
func (_u *MemoryUpdateOne) ClearMainType() *MemoryUpdateOne {
	_u.mutation.ClearMainType()
	return _u
}

// ClearSubType clears the "sub_type" edge to the SubType entity.
func (_u *MemoryUpdateOne) ClearSubType() *MemoryUpdateOne {
	_u.mutation.ClearSubType()
	return _u
}

// Where appends a list predicates to the MemoryUpdate builder.
func (_u *MemoryUpdateOne) Where(ps ...predicate.Memory) *MemoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoryUpdateOne) Select(field string, fields ...string) *MemoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Memory entity.
func (_u *MemoryUpdateOne) Save(ctx context.Context) (*Memory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryUpdateOne) SaveX(ctx context.Context) *Memory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := memory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Memory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := memory.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Memory.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Price(); ok {
		if err := memory.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Memory.price": %w`, err)}
		}
	}
	if _u.mutation.MainTypeCleared() && len(_u.mutation.MainTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.main_type"`)
	}
	if _u.mutation.SubTypeCleared() && len(_u.mutation.SubTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memory.sub_type"`)
	}
	return nil
}

func (_u *MemoryUpdateOne) sqlSave(ctx context.Context) (_node *Memory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memory.Table, memory.Columns, sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Memory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memory.FieldID)
		for _, f := range fields {
			if !memory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(memory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(memory.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(memory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(memory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MainTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.MainTypeTable,
			Columns: []string{memory.MainTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MainTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.MainTypeTable,
			Columns: []string{memory.MainTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.SubTypeTable,
			Columns: []string{memory.SubTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   memory.SubTypeTable,
			Columns: []string{memory.SubTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Memory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
