// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/schema"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
	"github.com/LucasMadranges/MapMemory/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	maintypeFields := schema.MainType{}.Fields()
	_ = maintypeFields
	// maintypeDescName is the schema descriptor for name field.
	maintypeDescName := maintypeFields[0].Descriptor()
	// maintype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	maintype.NameValidator = func() func(string) error {
		validators := maintypeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// maintypeDescColor is the schema descriptor for color field.
	maintypeDescColor := maintypeFields[1].Descriptor()
	// maintype.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	maintype.ColorValidator = func() func(string) error {
		validators := maintypeDescColor.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(color string) error {
			for _, fn := range fns {
				if err := fn(color); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	memoryFields := schema.Memory{}.Fields()
	_ = memoryFields
	// memoryDescName is the schema descriptor for name field.
	memoryDescName := memoryFields[0].Descriptor()
	// memory.NameValidator is a validator for the "name" field. It is called by the builders before save.
	memory.NameValidator = func() func(string) error {
		validators := memoryDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// memoryDescDescription is the schema descriptor for description field.
	memoryDescDescription := memoryFields[1].Descriptor()
	// memory.DefaultDescription holds the default value on creation for the description field.
	memory.DefaultDescription = memoryDescDescription.Default.(string)
	// memory.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	memory.DescriptionValidator = func() func(string) error {
		validators := memoryDescDescription.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(description string) error {
			for _, fn := range fns {
				if err := fn(description); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// memoryDescPrice is the schema descriptor for price field.
	memoryDescPrice := memoryFields[2].Descriptor()
	// memory.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	memory.PriceValidator = memoryDescPrice.Validators[0].(func(float64) error)
	// memoryDescCreatedAt is the schema descriptor for created_at field.
	memoryDescCreatedAt := memoryFields[3].Descriptor()
	// memory.DefaultCreatedAt holds the default value on creation for the created_at field.
	memory.DefaultCreatedAt = memoryDescCreatedAt.Default.(func() time.Time)
	// memoryDescUpdatedAt is the schema descriptor for updated_at field.
	memoryDescUpdatedAt := memoryFields[4].Descriptor()
	// memory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memory.DefaultUpdatedAt = memoryDescUpdatedAt.Default.(func() time.Time)
	// memory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memory.UpdateDefaultUpdatedAt = memoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	subtypeFields := schema.SubType{}.Fields()
	_ = subtypeFields
	// subtypeDescName is the schema descriptor for name field.
	subtypeDescName := subtypeFields[0].Descriptor()
	// subtype.NameValidator is a validator for the "name" field. It is called by the builders before save.
	subtype.NameValidator = func() func(string) error {
		validators := subtypeDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// subtypeDescColor is the schema descriptor for color field.
	subtypeDescColor := subtypeFields[1].Descriptor()
	// subtype.ColorValidator is a validator for the "color" field. It is called by the builders before save.
	subtype.ColorValidator = func() func(string) error {
		validators := subtypeDescColor.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(color string) error {
			for _, fn := range fns {
				if err := fn(color); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescFirstname is the schema descriptor for firstname field.
	userDescFirstname := userFields[3].Descriptor()
	// user.FirstnameValidator is a validator for the "firstname" field. It is called by the builders before save.
	user.FirstnameValidator = func() func(string) error {
		validators := userDescFirstname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(firstname string) error {
			for _, fn := range fns {
				if err := fn(firstname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLastname is the schema descriptor for lastname field.
	userDescLastname := userFields[4].Descriptor()
	// user.LastnameValidator is a validator for the "lastname" field. It is called by the builders before save.
	user.LastnameValidator = func() func(string) error {
		validators := userDescLastname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(lastname string) error {
			for _, fn := range fns {
				if err := fn(lastname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[5].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[6].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = func() func(string) error {
		validators := userDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
			validators[3].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
