// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/predicate"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// SubTypeQuery is the builder for querying SubType entities.
type SubTypeQuery struct {
	config
	ctx           *QueryContext
	order         []subtype.OrderOption
	inters        []Interceptor
	predicates    []predicate.SubType
	withMainTypes *MainTypeQuery
	withMemories  *MemoryQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubTypeQuery builder.
func (_q *SubTypeQuery) Where(ps ...predicate.SubType) *SubTypeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubTypeQuery) Limit(limit int) *SubTypeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubTypeQuery) Offset(offset int) *SubTypeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubTypeQuery) Unique(unique bool) *SubTypeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubTypeQuery) Order(o ...subtype.OrderOption) *SubTypeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMainTypes chains the current query on the "main_types" edge.
func (_q *SubTypeQuery) QueryMainTypes() *MainTypeQuery {
	query := (&MainTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subtype.Table, subtype.FieldID, selector),
			sqlgraph.To(maintype.Table, maintype.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, subtype.MainTypesTable, subtype.MainTypesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMemories chains the current query on the "memories" edge.
func (_q *SubTypeQuery) QueryMemories() *MemoryQuery {
	query := (&MemoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(subtype.Table, subtype.FieldID, selector),
			sqlgraph.To(memory.Table, memory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, subtype.MemoriesTable, subtype.MemoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SubType entity from the query.
// Returns a *NotFoundError when no SubType was found.
func (_q *SubTypeQuery) First(ctx context.Context) (*SubType, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subtype.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubTypeQuery) FirstX(ctx context.Context) *SubType {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubType ID from the query.
// Returns a *NotFoundError when no SubType ID was found.
func (_q *SubTypeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subtype.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubTypeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubType entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubType entity is found.
// Returns a *NotFoundError when no SubType entities are found.
func (_q *SubTypeQuery) Only(ctx context.Context) (*SubType, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subtype.Label}
	default:
		return nil, &NotSingularError{subtype.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubTypeQuery) OnlyX(ctx context.Context) *SubType {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubType ID in the query.
// Returns a *NotSingularError when more than one SubType ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubTypeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subtype.Label}
	default:
		err = &NotSingularError{subtype.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubTypeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubTypes.
func (_q *SubTypeQuery) All(ctx context.Context) ([]*SubType, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubType, *SubTypeQuery]()
	return withInterceptors[[]*SubType](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubTypeQuery) AllX(ctx context.Context) []*SubType {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubType IDs.
func (_q *SubTypeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subtype.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubTypeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubTypeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubTypeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubTypeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubTypeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubTypeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubTypeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubTypeQuery) Clone() *SubTypeQuery {
	if _q == nil {
		return nil
	}
	return &SubTypeQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]subtype.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.SubType{}, _q.predicates...),
		withMainTypes: _q.withMainTypes.Clone(),
		withMemories:  _q.withMemories.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMainTypes tells the query-builder to eager-load the nodes that are connected to
// the "main_types" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubTypeQuery) WithMainTypes(opts ...func(*MainTypeQuery)) *SubTypeQuery {
	query := (&MainTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMainTypes = query
	return _q
}

// WithMemories tells the query-builder to eager-load the nodes that are connected to
// the "memories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SubTypeQuery) WithMemories(opts ...func(*MemoryQuery)) *SubTypeQuery {
	query := (&MemoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMemories = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubType.Query().
//		GroupBy(subtype.FieldLabel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubTypeQuery) GroupBy(field string, fields ...string) *SubTypeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubTypeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subtype.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Label string `json:"label,omitempty"`
//	}
//
//	client.SubType.Query().
//		Select(subtype.FieldLabel).
//		Scan(ctx, &v)
func (_q *SubTypeQuery) Select(fields ...string) *SubTypeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubTypeSelect{SubTypeQuery: _q}
	sbuild.label = subtype.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubTypeSelect configured with the given aggregations.
func (_q *SubTypeQuery) Aggregate(fns ...AggregateFunc) *SubTypeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubTypeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subtype.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubTypeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubType, error) {
	var (
		nodes       = []*SubType{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withMainTypes != nil,
			_q.withMemories != nil,
		}
	)
	if _q.withMainTypes != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, subtype.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubType).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubType{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMainTypes; query != nil {
		if err := _q.loadMainTypes(ctx, query, nodes, nil,
			func(n *SubType, e *MainType) { n.Edges.MainTypes = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMemories; query != nil {
		if err := _q.loadMemories(ctx, query, nodes,
			func(n *SubType) { n.Edges.Memories = []*Memory{} },
			func(n *SubType, e *Memory) { n.Edges.Memories = append(n.Edges.Memories, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SubTypeQuery) loadMainTypes(ctx context.Context, query *MainTypeQuery, nodes []*SubType, init func(*SubType), assign func(*SubType, *MainType)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SubType)
	for i := range nodes {
		if nodes[i].main_type_id == nil {
			continue
		}
		fk := *nodes[i].main_type_id
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(maintype.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "main_type_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SubTypeQuery) loadMemories(ctx context.Context, query *MemoryQuery, nodes []*SubType, init func(*SubType), assign func(*SubType, *Memory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SubType)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Memory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(subtype.MemoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sub_type_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "sub_type_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sub_type_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SubTypeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubTypeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subtype.Table, subtype.Columns, sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subtype.FieldID)
		for i := range fields {
			if fields[i] != subtype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubTypeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subtype.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subtype.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubTypeGroupBy is the group-by builder for SubType entities.
type SubTypeGroupBy struct {
	selector
	build *SubTypeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubTypeGroupBy) Aggregate(fns ...AggregateFunc) *SubTypeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubTypeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubTypeQuery, *SubTypeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubTypeGroupBy) sqlScan(ctx context.Context, root *SubTypeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubTypeSelect is the builder for selecting fields of SubType entities.
type SubTypeSelect struct {
	*SubTypeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubTypeSelect) Aggregate(fns ...AggregateFunc) *SubTypeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubTypeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubTypeQuery, *SubTypeSelect](ctx, _s.SubTypeQuery, _s, _s.inters, v)
}

func (_s *SubTypeSelect) sqlScan(ctx context.Context, root *SubTypeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
