// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/memory"
	"github.com/LucasMadranges/MapMemory/ent/predicate"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// SubTypeUpdate is the builder for updating SubType entities.
type SubTypeUpdate struct {
	config
	hooks    []Hook
	mutation *SubTypeMutation
}

// Where appends a list predicates to the SubTypeUpdate builder.
func (_u *SubTypeUpdate) Where(ps ...predicate.SubType) *SubTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SubTypeUpdate) SetName(v string) *SubTypeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubTypeUpdate) SetNillableName(v *string) *SubTypeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SubTypeUpdate) SetColor(v string) *SubTypeUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SubTypeUpdate) SetNillableColor(v *string) *SubTypeUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetMainTypesID sets the "main_types" edge to the MainType entity by ID.
func (_u *SubTypeUpdate) SetMainTypesID(id int) *SubTypeUpdate {
	_u.mutation.SetMainTypesID(id)
	return _u
}

// SetMainTypes sets the "main_types" edge to the MainType entity.
func (_u *SubTypeUpdate) SetMainTypes(v *MainType) *SubTypeUpdate {
	return _u.SetMainTypesID(v.ID)
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_u *SubTypeUpdate) AddMemoryIDs(ids ...int) *SubTypeUpdate {
	_u.mutation.AddMemoryIDs(ids...)
	return _u
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_u *SubTypeUpdate) AddMemories(v ...*Memory) *SubTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryIDs(ids...)
}

// Mutation returns the SubTypeMutation object of the builder.
func (_u *SubTypeUpdate) Mutation() *SubTypeMutation {
	return _u.mutation
}

// ClearMainTypes clears the "main_types" edge to the MainType entity.
func (_u *SubTypeUpdate) ClearMainTypes() *SubTypeUpdate {
	_u.mutation.ClearMainTypes()
	return _u
}

// ClearMemories clears all "memories" edges to the Memory entity.
func (_u *SubTypeUpdate) ClearMemories() *SubTypeUpdate {
	_u.mutation.ClearMemories()
	return _u
}

// RemoveMemoryIDs removes the "memories" edge to Memory entities by IDs.
func (_u *SubTypeUpdate) RemoveMemoryIDs(ids ...int) *SubTypeUpdate {
	_u.mutation.RemoveMemoryIDs(ids...)
	return _u
}

// RemoveMemories removes "memories" edges to Memory entities.
func (_u *SubTypeUpdate) RemoveMemories(v ...*Memory) *SubTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubTypeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subtype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := subtype.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "SubType.color": %w`, err)}
		}
	}
	if _u.mutation.MainTypesCleared() && len(_u.mutation.MainTypesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubType.main_types"`)
	}
	return nil
}

func (_u *SubTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subtype.Table, subtype.Columns, sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subtype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(subtype.FieldColor, field.TypeString, value)
	}
	if _u.mutation.MainTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtype.MainTypesTable,
			Columns: []string{subtype.MainTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MainTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtype.MainTypesTable,
			Columns: []string{subtype.MainTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   subtype.MemoriesTable,
			Columns: []string{subtype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoriesIDs(); len(nodes) > 0 && !_u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   subtype.MemoriesTable,
			Columns: []string{subtype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   subtype.MemoriesTable,
			Columns: []string{subtype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subtype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubTypeUpdateOne is the builder for updating a single SubType entity.
type SubTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubTypeMutation
}

// SetName sets the "name" field.
func (_u *SubTypeUpdateOne) SetName(v string) *SubTypeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubTypeUpdateOne) SetNillableName(v *string) *SubTypeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SubTypeUpdateOne) SetColor(v string) *SubTypeUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SubTypeUpdateOne) SetNillableColor(v *string) *SubTypeUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// SetMainTypesID sets the "main_types" edge to the MainType entity by ID.
func (_u *SubTypeUpdateOne) SetMainTypesID(id int) *SubTypeUpdateOne {
	_u.mutation.SetMainTypesID(id)
	return _u
}

// SetMainTypes sets the "main_types" edge to the MainType entity.
func (_u *SubTypeUpdateOne) SetMainTypes(v *MainType) *SubTypeUpdateOne {
	return _u.SetMainTypesID(v.ID)
}

// AddMemoryIDs adds the "memories" edge to the Memory entity by IDs.
func (_u *SubTypeUpdateOne) AddMemoryIDs(ids ...int) *SubTypeUpdateOne {
	_u.mutation.AddMemoryIDs(ids...)
	return _u
}

// AddMemories adds the "memories" edges to the Memory entity.
func (_u *SubTypeUpdateOne) AddMemories(v ...*Memory) *SubTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemoryIDs(ids...)
}

// Mutation returns the SubTypeMutation object of the builder.
func (_u *SubTypeUpdateOne) Mutation() *SubTypeMutation {
	return _u.mutation
}

// ClearMainTypes clears the "main_types" edge to the MainType entity.
func (_u *SubTypeUpdateOne) ClearMainTypes() *SubTypeUpdateOne {
	_u.mutation.ClearMainTypes()
	return _u
}

// ClearMemories clears all "memories" edges to the Memory entity.
func (_u *SubTypeUpdateOne) ClearMemories() *SubTypeUpdateOne {
	_u.mutation.ClearMemories()
	return _u
}

// RemoveMemoryIDs removes the "memories" edge to Memory entities by IDs.
func (_u *SubTypeUpdateOne) RemoveMemoryIDs(ids ...int) *SubTypeUpdateOne {
	_u.mutation.RemoveMemoryIDs(ids...)
	return _u
}

// RemoveMemories removes "memories" edges to Memory entities.
func (_u *SubTypeUpdateOne) RemoveMemories(v ...*Memory) *SubTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemoryIDs(ids...)
}

// Where appends a list predicates to the SubTypeUpdate builder.
func (_u *SubTypeUpdateOne) Where(ps ...predicate.SubType) *SubTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubTypeUpdateOne) Select(field string, fields ...string) *SubTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubType entity.
func (_u *SubTypeUpdateOne) Save(ctx context.Context) (*SubType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubTypeUpdateOne) SaveX(ctx context.Context) *SubType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subtype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SubType.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := subtype.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "SubType.color": %w`, err)}
		}
	}
	if _u.mutation.MainTypesCleared() && len(_u.mutation.MainTypesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SubType.main_types"`)
	}
	return nil
}

func (_u *SubTypeUpdateOne) sqlSave(ctx context.Context) (_node *SubType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subtype.Table, subtype.Columns, sqlgraph.NewFieldSpec(subtype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subtype.FieldID)
		for _, f := range fields {
			if !subtype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subtype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subtype.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(subtype.FieldColor, field.TypeString, value)
	}
	if _u.mutation.MainTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtype.MainTypesTable,
			Columns: []string{subtype.MainTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MainTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subtype.MainTypesTable,
			Columns: []string{subtype.MainTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(maintype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   subtype.MemoriesTable,
			Columns: []string{subtype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemoriesIDs(); len(nodes) > 0 && !_u.mutation.MemoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   subtype.MemoriesTable,
			Columns: []string{subtype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   subtype.MemoriesTable,
			Columns: []string{subtype.MemoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subtype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
