// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LucasMadranges/MapMemory/ent/maintype"
	"github.com/LucasMadranges/MapMemory/ent/subtype"
)

// SubType is the model entity for the SubType schema.
type SubType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubTypeQuery when eager-loading is set.
	Edges        SubTypeEdges `json:"edges"`
	main_type_id *int
	selectValues sql.SelectValues
}

// SubTypeEdges holds the relations/edges for other nodes in the graph.
type SubTypeEdges struct {
	// MainTypes holds the value of the main_types edge.
	MainTypes *MainType `json:"main_types,omitempty"`
	// Memories holds the value of the memories edge.
	Memories []*Memory `json:"memories,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MainTypesOrErr returns the MainTypes value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubTypeEdges) MainTypesOrErr() (*MainType, error) {
	if e.MainTypes != nil {
		return e.MainTypes, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: maintype.Label}
	}
	return nil, &NotLoadedError{edge: "main_types"}
}

// MemoriesOrErr returns the Memories value or an error if the edge
// was not loaded in eager-loading.
func (e SubTypeEdges) MemoriesOrErr() ([]*Memory, error) {
	if e.loadedTypes[1] {
		return e.Memories, nil
	}
	return nil, &NotLoadedError{edge: "memories"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subtype.FieldID:
			values[i] = new(sql.NullInt64)
		case subtype.FieldName:
			values[i] = new(sql.NullString)
		case subtype.ForeignKeys[0]: // main_type_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubType fields.
func (_m *SubType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subtype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case subtype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case subtype.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field main_type_id", value)
			} else if value.Valid {
				_m.main_type_id = new(int)
				*_m.main_type_id = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubType.
// This includes values selected through modifiers, order, etc.
func (_m *SubType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMainTypes queries the "main_types" edge of the SubType entity.
func (_m *SubType) QueryMainTypes() *MainTypeQuery {
	return NewSubTypeClient(_m.config).QueryMainTypes(_m)
}

// QueryMemories queries the "memories" edge of the SubType entity.
func (_m *SubType) QueryMemories() *MemoryQuery {
	return NewSubTypeClient(_m.config).QueryMemories(_m)
}

// Update returns a builder for updating this SubType.
// Note that you need to call SubType.Unwrap() before calling this method if this SubType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubType) Update() *SubTypeUpdateOne {
	return NewSubTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubType) Unwrap() *SubType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubType) String() string {
	var builder strings.Builder
	builder.WriteString("SubType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// SubTypes is a parsable slice of SubType.
type SubTypes []*SubType
