name: Static Code Security Scan

on:
  pull_request:
  push:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep_scan:
    name: Semgrep Scan (JS/TS/Go)
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        # On scanne tout le code
        run: |
          semgrep scan \
            --config p/javascript \
            --config p/typescript \
            --config p/security-audit \
            --sarif \
            --output semgrep.sarif .

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
